"""
internal/engines/exergy.py — Thermodynamic Capital Accounting (Exergy Gate)

Tier 5 DRAFT — 888 HOLD ACTIVE

Closes the WEALTH TODO.md line-90 gap: "Thermodynamic capital accounting —
exergy + negentropy capital types."

This module is NOT ratified constitutional law. It is a draft engine under
888 HOLD. Any SEAL verdict that depends on it must be explicitly reviewed
by F13.

Formula (from Substrate Reference Layer, DRAFT):
    Ξ = NPV_realized / (Allocated_Capital * (1 + ΔS_allocation))
    η_x = Ξ / Allocated_Capital

Gate:
    η_x >= 0.70  → SEAL / QUALIFY
    η_x < 0.70   → VOID (heat waste)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


class ExergyError(Exception):
    """Base for exergy-gate violations. Verdict = VOID (heat waste)."""

    def __init__(self, message: str, eta_x: float):
        super().__init__(message)
        self.eta_x = eta_x


@dataclass
class ExergyResult:
    """Canonical result of an exergy calculation."""

    xi: float
    eta_x: float
    npv_realized: float
    allocated_capital: float
    delta_s_allocation: float
    heat_waste: float
    meets_threshold: bool
    verdict: str
    tier: str = "DRAFT — TIER 5 (Governance Doctrine) — 888 HOLD ACTIVE"

    def to_dict(self) -> dict[str, Any]:
        return {
            "xi": self.xi,
            "eta_x": self.eta_x,
            "npv_realized": self.npv_realized,
            "allocated_capital": self.allocated_capital,
            "delta_s_allocation": self.delta_s_allocation,
            "heat_waste": self.heat_waste,
            "meets_threshold": self.meets_threshold,
            "verdict": self.verdict,
            "tier": self.tier,
        }


def calculate_exergy(
    npv_realized: float,
    allocated_capital: float,
    delta_s_allocation: float = 0.0,
) -> ExergyResult:
    """
    Compute capital exergy and the η_x ratio.

    Args:
        npv_realized: Net Present Value generated by the allocation.
        allocated_capital: Total capital or compute resources deployed.
        delta_s_allocation: Entropy increase caused by the decision [0, ∞).

    Returns:
        ExergyResult with verdict.

    Raises:
        ValueError: If allocated_capital is not positive.
    """
    if allocated_capital <= 0:
        raise ValueError("allocated_capital must be positive.")

    denominator = allocated_capital * (1.0 + max(delta_s_allocation, 0.0))
    xi = npv_realized / denominator
    eta_x = xi / allocated_capital
    heat_waste = max(0.0, allocated_capital - npv_realized)
    meets = eta_x >= 0.70
    verdict = "SEAL" if meets else "VOID"

    return ExergyResult(
        xi=xi,
        eta_x=eta_x,
        npv_realized=npv_realized,
        allocated_capital=allocated_capital,
        delta_s_allocation=delta_s_allocation,
        heat_waste=heat_waste,
        meets_threshold=meets,
        verdict=verdict,
    )


def exergy_gate(
    npv_realized: float,
    allocated_capital: float,
    delta_s_allocation: float = 0.0,
    raise_on_heat_waste: bool = True,
) -> dict[str, Any]:
    """
    Enforce the η_x >= 0.70 gate before a capital SEAL.

    Args:
        raise_on_heat_waste: If True, raise ExergyError when η_x < 0.70.
                             Set False for audit/reporting callers.

    Returns:
        Dict with full exergy report.

    Raises:
        ExergyError: If η_x < 0.70 and raise_on_heat_waste is True.
    """
    result = calculate_exergy(npv_realized, allocated_capital, delta_s_allocation)

    if not result.meets_threshold and raise_on_heat_waste:
        raise ExergyError(
            f"Exergy gate VIOLATED: η_x={result.eta_x:.4f} < 0.70. "
            f"Capital allocation is heat waste (VOID).",
            eta_x=result.eta_x,
        )

    return result.to_dict()


def downgrade_verdict_by_exergy(
    current_verdict: str,
    npv_realized: float,
    allocated_capital: float,
    delta_s_allocation: float = 0.0,
) -> dict[str, Any]:
    """
    Downgrade any WEALTH verdict to VOID if the exergy gate fails.

    Non-blocking: always returns a report and the adjusted verdict.
    """
    try:
        gate = exergy_gate(
            npv_realized, allocated_capital, delta_s_allocation, raise_on_heat_waste=True
        )
        return {
            "original_verdict": current_verdict,
            "adjusted_verdict": current_verdict,
            "exergy": gate,
        }
    except ExergyError as exc:
        return {
            "original_verdict": current_verdict,
            "adjusted_verdict": "VOID",
            "exergy": {
                "xi": 0.0,
                "eta_x": exc.eta_x,
                "npv_realized": npv_realized,
                "allocated_capital": allocated_capital,
                "delta_s_allocation": delta_s_allocation,
                "heat_waste": max(0.0, allocated_capital - npv_realized),
                "meets_threshold": False,
                "verdict": "VOID",
                "tier": "DRAFT — TIER 5 (Governance Doctrine) — 888 HOLD ACTIVE",
            },
            "rationale": str(exc),
        }
